#

diff --git a/buildspec_owasp_dependency_check.yml b/buildspec_owasp_dependency_check.yml
--- a/buildspec_owasp_dependency_check.yml
+++ b/buildspec_owasp_dependency_check.yml
@@ -30,11 +30,12 @@ phases:
         \"build_id\": env.CODEBUILD_BUILD_ID, \
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" dependency-check-report.json > payload.json
+      - base64 -w 0 payload.json > payload_base64.txt
       - pwd && ls && whoami
       - |
         if [[ $high_risk_dependency -gt 0 ]]; then
           echo "there are high or medium alerts.. failing the build"
-          aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload.json dependency-check-report.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload_base64.txt dependency-check-report.json && echo "LAMBDA_SUCCEEDED" || echo "LAMBDA_FAILED"
           exit 1; 
         fi
 artifacts:
