#

diff --git a/buildspec_owasp_dependency_check.yml b/buildspec_owasp_dependency_check.yml
--- a/buildspec_owasp_dependency_check.yml
+++ b/buildspec_owasp_dependency_check.yml
@@ -31,14 +31,13 @@ phases:
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" dependency-check-report.json > payload.json
       - pwd && ls && whoami
-      - |
-        if [[ $high_risk_dependency -gt 0 ]]; then
-          echo "there are high or medium alerts.. failing the build"
-          exit 1; 
-        fi
+      #- |
+      #  if [[ $high_risk_dependency -gt 0 ]]; then
+      #    echo "there are high or medium alerts.. failing the build"
+      #    exit 1; 
+      #  fi
 artifacts:
   files: $CODEBUILD_SRC_DIR/dependency-check/bin/*.json
 
   # aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload.json dependency-check-report.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
   # 위 코드는 lamda 함수 구현 시 exit 1; 위에 추가할 것 
-  
