#

diff --git a/buildspec_sonarqube.yml b/buildspec_sonarqube.yml
--- a/buildspec_sonarqube.yml
+++ b/buildspec_sonarqube.yml
@@ -25,3 +25,17 @@ phases:
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" sonarqube_scanreport.json > payload.json
       - "curl -s -u $SONAR_QUBE_KEY: $SONAR_QUBE_URL/api/qualitygates/project_status?projectKey=$SONAR_QUBE_PROJECT> /tmp/result.json"
+      - |
+        if [ $quality_status = "ERROR" ]; then
+          aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload.json sonarqube_scan_report.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          echo "in quality_status ERROR or WARN condition"
+          exit 1;
+        elif [ $quality_status = "OK" ]; then
+          echo "in quality_status OK condition"
+        else
+          echo "in quality_status  unexpected condition"
+          exit 1;
+        fi
+  artifacts:
+    type: zip
+    files: '**/*'
